### PR TITLE
Fix issue #12

### PR DESCRIPTION
**Pull request by iliaamiri**
## Addresses Issue https://github.com/meech-ward/might-fail/issues/12

The issue seems to be that we are including the "source maps" as part of the package in this line of `package.json`:
```js
  "files": [
    "dist"
  ],
```
However, the source map files are pointing to the `/src` folder of the package which is not included as part of the published package.

So, in order to exclude the `.map` files from the published version, we can be more specific about what's included by changing that line to:
```js
   "files": [
-    "dist"
+    "dist/**/*.js",
+    "dist/**/*.d.ts",
+    "dist/**/*.ts"
   ],
```

Accordin to Gpity, source maps are just useful for the bundlers to let devs debug easier by pointing to the actual readable version of the code, which I believe they should not to debug `might-fail` package.

### CODE REVIEW

**Comment by meech-ward** [comment]
did you rebase again?

`fatal: Not possible to fast-forward, aborting.`

**Comment by iliaamiri** [comment]
No, I merged. unless I was too sleepy to realize it said rebase. but i know that if was rebase, it would've said i have incoming changes so i'm 98% sure i merged

**Comment by meech-ward** [comment]
Maybe i just don't know how to use git

This doesn't fix the issue when running with bun and vinxi. No idea why, I can't figure it out.


```ts
"files": [
  "dist//*.js",
  "dist//.d.ts",
  "dist/**/.ts"
],
2:20:15 p.m. [vite] Error when evaluating SSR module /Users/sam/Playground/solid-might-fail/src/routes/index.tsx?pick=default&pick=$css: failed to import "might-fail"
|- Error: Cannot find module '/Users/sam/Playground/solid-might-fail/node_modules/might-fail/dist/mightFail' imported from /Users/sam/Playground/solid-might-fail/node_modules/might-fail/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

**Comment by iliaamiri** [comment]
Can it be because of the fact that import statement doesn't specify the .js extension? 

I've seen in libraries like SST, they always specify `.js` in their dist files. I wonder if that'd fix it. 

I should link the project locally to my bun solid.js project to test it myself. I'll try doing that later today. But, if you had time, I think it's worth specifying the `.js` extension to see if that'd fix it.  

image

**Comment by meech-ward** [comment]
yeah so it turns out npm kind of sucks for this and people have to do shitty workarounds. I've copied hono's solution that they took from someone else and made a built.ts file https://github.com/honojs/hono/blob/main/build.ts

so this should be fixed

side note, jsr solves all of this and just does the right things so i'm very tempted to put in teh docs "just use jsr"

**Pull request merged**
